included:
  - Source
  - Tests
excluded:
  - Tests/SourceKittenFrameworkTests/Fixtures
  - Source/SourceKittenFramework/library_wrapper_CXString.swift
  - Source/SourceKittenFramework/library_wrapper_Documentation.swift
  - Source/SourceKittenFramework/library_wrapper_Index.swift
  - Source/SourceKittenFramework/library_wrapper_sourcekitd.swift
disabled_rules:
  - force_cast
  - force_try
  - todo

line_length: 160
