included:
  - Source
  - Tests
disabled_rules:
  - comma
  - cyclomatic_complexity
  - file_length
  - force_cast
  - force_try
  - function_body_length
  - leading_whitespace
  - line_length
  - nesting
  - syntactic_sugar
  - todo
  - trailing_comma
  - trailing_newline
  - variable_name
  - vertical_whitespace
  - void_return
