included:
  - Source
  - Tests
excluded:
  - Tests/SourceKittenFrameworkTests/Fixtures
  - Source/SourceKittenFramework/library_wrapper_CXString.swift
  - Source/SourceKittenFramework/library_wrapper_Documentation.swift
  - Source/SourceKittenFramework/library_wrapper_Index.swift
  - Source/SourceKittenFramework/library_wrapper_sourcekitd.swift
disabled_rules:
  - file_length
  - force_cast
  - force_try
  - line_length
  - todo
  - trailing_comma
  - variable_name
