language: generic
matrix:
  include:
    - script:
        - make test
        - pod lib lint
      env: JOB=Xcode
      os: osx
      osx_image: xcode8.3
      before_install:
        - pod repo update
    - script:
        - swift package edit Yams --revision master
        - swift test
        - swiftlint
      env: JOB=SPM
      os: osx
      osx_image: xcode8.3
    - script:
        - docker run -v `pwd`:`pwd` -w `pwd` norionomura/sourcekit:31 swift package edit Yams --revision master
        - make docker_test
      env: JOB=Linux
      sudo: required
      services: docker
notifications:
  email: false
  slack: realmio:vPdpsG9NLDo2DNlbqtcMAQuE
